### ISSUE TITLE
Fix Compile for mingw-w64

### ISSUE THREAD

**Issue by czchmate** [drobilla/lilv#15]
I don't really know how to go through the process of submitting code changes so I just wanted to let you, the developer know that testbench compilation fails under mingw-w64 cross-compile when the wafscript tries to link to librt. To circumvent this I made a change to the code to make it link to libpthread for the clock_gettime function instead.

You had an exception to skip the librt link if the compile environment is MSVC, but if you add an if loop to link to libpthread when the compile environment is mingw-w64, it should work.

**Comment by czchmate** [comment]
I forgot to add that the development environment was Ubuntu (aka Linux) when I had to make these changes.

**Comment by drobilla** [comment]
https://gitlab.com/lv2/lv2kit/-/jobs/323777590
