### ISSUE TITLE
"modern includes" should be conditional

### ISSUE THREAD

**Issue by giuliomoro** [drobilla/lilv#17]
I think the changes introduced here https://github.com/drobilla/lilv/commit/84762e0bfbc76d45e3e5bcbd42a49bb63c539dd7 should be conditional to the system at hand.

Is this not something that could be detected by `waf`, which would then generate an appropriate `#define`? Also, strange enough, currently `./waf configure` works fine, but then it fails at compile time, which is also not the way it should be, IMHO.

**Comment by drobilla** [comment]
Sorry, git builds against git.  There is no consideration given for building lilv against old things.  Progress in general, and especially in this current transitional stage of things would be completely impossible with that restriction.  If you want to use lilv from git you will have to use everything else from git as well. They are developed in tandem and soon will not be separate at all.

**Comment by giuliomoro** [comment]
ok, in the meantime I managed to build `master` by simply `git revert 84762e0`, that's why I thought it would be easy to `#ifdef` that. I stand by the point that the relevant paths should be checked by `cmake`, and not fail at build time.

**Comment by drobilla** [comment]
... `cmake`?

The waf script checks for lv2 1.16.0, which should have the appropriate includes.
