### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by alextone** [drobilla/lilv#18]
Sorry Dave, it's not my day.

Another build error, this time with lilv.

[21/27] Linking build/liblilv-0.so
[22/27] Linking build/utils/lilv-bench
[23/27] Linking build/utils/lv2ls
[24/27] Linking build/utils/lv2info
[25/27] Linking build/utils/lv2apply
[26/27] Linking build/utils/lv2bench
./liblilv-0.so: undefined reference to `serd_free'
collect2: error: ld returned 1 exit status

./liblilv-0.so: undefined reference to `serd_free'
collect2: error: ld returned 1 exit status

./liblilv-0.so: undefined reference to `serd_free'
collect2: error: ld returned 1 exit status

./liblilv-0.so: undefined reference to `serd_free'
collect2: error: ld returned 1 exit status

./liblilv-0.so: undefined reference to `serd_free'
collect2: error: ld returned 1 exit status

Waf: Leaving directory `/home/alex/github/lilv/build'
Build failed
 -> task in 'utils/lilv-bench' failed with exit status 1 (run with -v to display more information)
 -> task in 'utils/lv2apply' failed with exit status 1 (run with -v to display more information)
 -> task in 'utils/lv2ls' failed with exit status 1 (run with -v to display more information)
 -> task in 'utils/lv2info' failed with exit status 1 (run with -v to display more information)
 -> task in 'utils/lv2bench' failed with exit status 1 (run with -v to display more information)

What have i done wrong here?

Alex.

**Comment by drobilla** [comment]
Your serd was too old.  Fixed in b05eaf6, thanks.
