### ISSUE TITLE
lilv_world_get_plugin_classes() misses various RDF classes

### ISSUE THREAD

**Issue by atsushieno** [drobilla/lilv#19]
I noticed that these classes are not returned by `lilv_world_get_plugin_classes()`:

- http://lv2plug.in/ns/ext/atom#Atom
- http://lv2plug.in/ns/ext/atom#Event
- http://lv2plug.in/ns/ext/event#Event
- http://lv2plug.in/ns/ext/event#TimeStamp
- http://lv2plug.in/ns/ext/log#Entry
- http://lv2plug.in/ns/ext/midi#Chunk
- http://lv2plug.in/ns/ext/patch#Message
- http://lv2plug.in/ns/ext/state#State
- http://lv2plug.in/ns/ext/time#Position
- http://lv2plug.in/ns/extensions/ui#UI
- http://lv2plug.in/ns/extensions/units#Unit
- http://lv2plug.in/ns/lv2core#ExtensionData
- http://lv2plug.in/ns/lv2core#Feature
- http://lv2plug.in/ns/lv2core#PluginBase
- http://lv2plug.in/ns/lv2core#Point
- http://lv2plug.in/ns/lv2core#PortProperty
- http://ontologi.es/doap-bugs#Issue
- http://purl.org/dc/terms/Agent
- http://purl.org/dc/terms/LinguisticSystem
- http://purl.org/dc/terms/MediaTypeOrExtent
- http://purl.org/dc/terms/RightsStatement
- http://purl.org/dc/terms/Standard
- http://usefulinc.com/ns/doap#Repository
- http://usefulinc.com/ns/doap#Version
- http://www.w3.org/2000/01/rdf-schema#Resource
- http://xmlns.com/foaf/0.1/Agent
- http://xmlns.com/foaf/0.1/Document
- http://xmlns.com/foaf/0.1/LabelProperty
- http://xmlns.com/foaf/0.1/Project

I assume this is not intended.

Here is a repro code (very simple enumeration):

```
#include <stdio.h>
#include "lilv/lilv.h"

int main ()
{
  int i, j;

  const LilvWorld *world = lilv_world_new ();

  lilv_world_load_bundle (world, lilv_new_uri (world, "http://www.w3.org/2000/01/rdf-schema"));

  lilv_world_load_all (world);

  const LilvPluginClasses *classes = lilv_world_get_plugin_classes (world);
  LILV_FOREACH(plugin_classes, i, classes) {
    const LilvPluginClass *c = lilv_plugin_classes_get (classes, i);
    puts (lilv_node_as_uri (lilv_plugin_class_get_uri (c)));
    const LilvPluginClasses *children = lilv_plugin_class_get_children (c);
    LILV_FOREACH(plugin_classes, j, children) {
      const LilvPluginClass *h = lilv_plugin_classes_get (children, j);
      printf ("  ");
      puts (lilv_node_as_uri (lilv_plugin_class_get_uri (h)));
    }
  }

  lilv_world_free (world);
}
```

It is because those classes does not have "parent" and `lilv_world_get_plugin_classes()` filters out such classes that do not have parent.

I will create a straightforward fix for this in a PR.

**Comment by drobilla** [comment]
?

Those are not _plugin_ classes.

**Comment by atsushieno** [comment]
Ah, so LV2 _pligins_ are not to necessarily represent LV2 _extensions_ that are stored as `lib/*.lv2`. Thanks for clarification.

**Comment by drobilla** [comment]
Right, this API is specifically about plugin classes ("categories").  If you want to do general RDF stuff you can use `lilv_world_find_nodes()` and similar world functions.

**Comment by atsushieno** [comment]
That sounds perfect. Thanks!
