### ISSUE TITLE
lilv_world_get_plugin_classes() misses label-less classes e.g. AmbisonicGroup

### ISSUE THREAD

**Issue by atsushieno** [drobilla/lilv#21]
It's similar to issue #19 - lilv_world_get_plugin_classes() skips plugin classes that do not have "label". Obviously it is intended (as per [*1]), but that results in some unexpected lack of results.

Here are the missing classes because of this:

- http://lv2plug.in/ns/ext/parameters#ControlGroup
- http://lv2plug.in/ns/ext/port-groups#AmbisonicGroup
- http://lv2plug.in/ns/ext/port-groups#DiscreteGroup
- http://lv2plug.in/ns/lv2core#Specification
- http://ontologi.es/doap-bugs#Issue

[*1] https://github.com/drobilla/lilv/blob/c1637b46f9ff960f58dcf2bb3b69bff231f8acfd/src/world.c#L1019

**Comment by drobilla** [comment]
This is deliberate.  Plugin classes need to have a label, since hosts are probably going to want to show one (most often, that's the only thing they are interested in doing).
