### ISSUE TITLE
lilv_world_get_plugin_classes() misses plugin classes whose parent is non-uri

### ISSUE THREAD

**Issue by atsushieno** [drobilla/lilv#22]
(Excuse me for these spammy reports!) Similar to issue #19 and issue #21, these plugin classes have SORD_BLANK as its parent node type and thus filtered by [*1] :

- http://lv2plug.in/ns/ext/dynmanifest#DynManifest : 
- http://lv2plug.in/ns/ext/port-groups#Element : 2
- http://lv2plug.in/ns/ext/port-groups#Group : 2
- http://lv2plug.in/ns/ext/presets#Bank : 2
- http://lv2plug.in/ns/extensions/ui#PortNotification : 2
- http://lv2plug.in/ns/extensions/units#Conversion : 2
- http://lv2plug.in/ns/lv2core#PortBase : 2

Again, I assume this is not an intended behavior.

Simply removing the filter condition at [*1] brings them back.

[*1] https://github.com/drobilla/lilv/blob/c1637b46f9ff960f58dcf2bb3b69bff231f8acfd/src/world.c#L1013

**Comment by drobilla** [comment]
LV2 does not support blank plugin classes.
