### ISSUE TITLE
Improper behaviour when saving/restoring Strings with LV2:State interface

### ISSUE THREAD

**Issue by sadko4u** [drobilla/lilv#24]
When trying to store multiple strings:
```
/scene/object/4/material/sound_speed
/scene/object/4/material/transparency/inner
/scene/object/4/material/dissipation/inner
/scene/object/4/material/dispersion/inner
/scene/object/4/material/absorption/inner
```
with same key: "http://lsp-plug.in/kvt#keys" we get the following result:
```
        state:state [
                <http://lsp-plug.in/kvt#keys> "/scene/object/4/material/sound_speed" ,
                        "/scene/object/4/material/transparency/inner" ,
                        "/scene/object/4/material/dissipation/inner" ,
                        "/scene/object/4/material/dispersion/inner" ,
                        "/scene/object/4/material/absorption/inner";
        ]
```

When reading LV2 state, we get only one random parameter, all other string parts are omitted:
```
[TRC][/home/vsadovnikov/eclipse/lsp-plugins/include/container/lv2/extensions.h: 569] retrieve_value: retrieve(57 (http://lsp-plug.in/kvt#keys))
[TRC][/home/vsadovnikov/eclipse/lsp-plugins/include/container/lv2/extensions.h: 571] retrieve_value: retrieved ptr = 0x9a959c0, size=44, type=41, flags=0x3
Received KVT key set:
00000000: 2f 73 63 65 6e 65 2f 6f 62 6a 65 63 74 2f 32 2f    /scene/object/2/
00000010: 6d 61 74 65 72 69 61 6c 2f 74 72 61 6e 73 70 61    material/transpa
00000020: 72 65 6e 63 79 2f 6f 75 74 65 72 00                rency/outer.
```

There is currently no way to fetch all the strings with same key while the LV2:State interface allows to store multiple values associated with the same key.

**Comment by drobilla** [comment]
The short answer, I'm afraid, is: don't do that.  While you _can_ have several values for a single property in RDF in general (as you do here), it generally makes everything massively more of a pain to work with (such as anything with a getter like this), so for the most part we just don't in LV2 things.  People tend to get confused about "order" (which is not a thing) when this is present as well.  Even if the interface supported it, I wouldn't recommend doing it.

The solution/workaround is to use a list.

**Comment by sadko4u** [comment]
Is there any way to protect host from such usage? For example, to ignore the second and more values and to write the proper message to **stderr**?

**Comment by drobilla** [comment]
It could return an error if the key is already set, I suppose.

There's only really 3 options that I can see:

1. Write them all, only allow access to one (as a consequence of the state API, current behaviour).
2. Write the first, return error on any other store calls that attempt to write it again.
3. Overwrite the current value (act like a setter).

1 is pretty crap, either of 2 or 3 seem reasonable.  2 seems least confusing, though is a bit more limiting than 3.

**Comment by sadko4u** [comment]
I think 2 is the best option.

**Comment by drobilla** [comment]
6d09956
