### ISSUE TITLE
[FR/QUESTION] Can lilv (Python binding) be used to send MIDI atoms to a plugin port?

### ISSUE THREAD

**Issue by SpotlightKid** [drobilla/lilv#26]
If so, can you give a short example, how to achieve this? Is there any code in lilv (or another library, which can be used from Python) to help construct MIDI atoms (I suppose one could always use the `struct` module or `ctypes`)?

If not, would you consider adding such a feature?

The main use case would be to be able to write automated tests for MIDI processing/filter LV2 plugins.

**Comment by drobilla** [comment]
Unfortunately, no, as far as I know nobody has written Python bindings for that stuff yet.  I agree it would be nice for tests though.

**Comment by SpotlightKid** [comment]
But there are already functions in lilv for that? Is there a C example I could look at? Adding new Python bindings with ctypes for existing functions is no problem for me.

**Comment by drobilla** [comment]
Most of the code for that is in LV2 https://github.com/drobilla/lv2/tree/master/lv2/atom though for MIDI there isn't really any code at all, it's an atom header just followed by straight MIDI.

You can find examples of writing to a sequence input in a bunch of places, here's one: https://github.com/drobilla/jalv/blob/master/src/lv2_evbuf.c#L154
