### ISSUE TITLE
[FR/QUESTION] (How) Can lilv (Python binding) launch embedded UIs of a plugin?

### ISSUE THREAD

**Issue by KannebTo** [drobilla/lilv#29]
I can get the file path of the UI implementation using `ui.get_binary_uri()` (eg. `file:///usr/lib/lv2/eg-scope.lv2/examploscope_ui.so` which is a GTK interface).
But it is not clear to me how to run and manage it properly.
My host don't have a GUI itself. Is it possible to launch it as a standalone window?
Maybe i have to somehow call the [LV2UI_Show_Interface](http://lv2plug.in/doc/html/group__ui.html#structLV2UI__Show__Interface)?

**Comment by mfisher31** [comment]
I don't use the python bindings, but the C library isn't used for displaying UIs.  You'll need `suil` for that.  Nutshell, use lilv to get UI information which is later passed to suil functions for instantiation.

**Comment by KannebTo** [comment]
Thank you for the hint. I didn't know [Suil](https://drobilla.net/software/suil) before. I'll check it out.

**Comment by mfisher31** [comment]
No problem @KannebTo

**Comment by drobilla** [comment]
If the show interface is implemented by the UI, that might work, but AFAIK nobody has implemented a simple interface for just showing a UI however.  This kind of thing got really sidetracked by the (IMO misguided) external UI stuff for years.

It could probably be implemented in (or using) suil, but to support processes with no GUI at all, that's quite some work, with another process, IPC, etc.
