### ISSUE TITLE
SEGV with python-lilv

### ISSUE THREAD

**Issue by dcoredump** [drobilla/lilv#4]
Hi David,

I am trying to use the python interface of lilv and wrote a simple program which gives me the URI and name of each preset for a given URI of a plugin:

```
#!/usr/bin/python3

#PLUGIN="https://github.com/dcoredump/dexed.lv2"
PLUGIN="http://tytel.org/helm"

import lilv
import pprint

world = lilv.World()
world.load_all()
plugin = world.get_all_plugins().get_by_uri(world.new_uri(PLUGIN))
preset_uri = lilv.Node(world.new_uri("http://lv2plug.in/ns/ext/presets#Preset"))
psets = plugin.get_related(preset_uri)
label_uri = world.new_uri(lilv.LILV_NS_RDFS + "label")
print(lilv.LILV_NS_RDFS + "label")
for pset_node in psets:
    print(pset_node.get_turtle_token())
    pset_nodes=world.find_nodes(pset_node,label_uri,None)
    for pset_name in pset_nodes:
        print(pset_name.get_turtle_token())
```

When running this I get a SEGV at the end:

```
....................
<http://tytel.org/helm#preset101>
SF Brass CC2
<http://tytel.org/helm#preset102>
SF Brass Soft Stutter
Segmentation fault
```

I don't know if I am doing something wrong or if there is a problem with python-lilv... can you take a look at this?

Thanks && Regards, Holger

[EDIT]
I found out that commenting out `node_free(self.node)` (lilv.py: 728) avoids the SEGV... but I think this is not a really nice solution...

**Comment by drobilla** [comment]
On Wed, 2017-11-08 at 06:54 +0000, Holger wrote:
> Hi David,
> I am trying to use the python interface of lilv and wrote a simple
> program which gives me the URI and name of each preset for a given
> URI of a plugin:
> #!/usr/bin/python3
> 
> #PLUGIN="https://github.com/dcoredump/dexed.lv2"
> PLUGIN="http://tytel.org/helm"
> 
> import lilv
> import pprint
> 
> world = lilv.World()
> world.load_all()
> plugin = world.get_all_plugins().get_by_uri(world.new_uri(PLUGIN))
> preset_uri = lilv.Node(world.new_uri("http://lv2plug.in/ns/ext/preset
> s#Preset"))
> psets = plugin.get_related(preset_uri)
> label_uri = world.new_uri(lilv.LILV_NS_RDFS + "label")
> print(lilv.LILV_NS_RDFS + "label")
> for pset_node in psets:
>     print(pset_node.get_turtle_token())
>     pset_nodes=world.find_nodes(pset_node,label_uri,None)
>     for pset_name in pset_nodes:
>         print(pset_name.get_turtle_token())
> When running this I get a SEGV at the end:
> ....................
> <http://tytel.org/helm#preset101>
> SF Brass CC2
> <http://tytel.org/helm#preset102>
> SF Brass Soft Stutter
> Segmentation fault
> I don't know if I am doing something wrong or if there is a problem
> with python-lilv... can you take a look at this?

Both, in a sense.  You shouldn't be explicitly creating a lilv.Node
like that, remove that so you just set preset_uri = world.new_uri(...)
and everything should work fine.

Of course, this should be either impossible or safe to do with the
bindings, but I don't know how to make that happen off the top of my
head.

-- 
dr

**Comment by SpotlightKid** [comment]
Here's a working script that lists plugin presets:

https://github.com/SpotlightKid/jack-audio-tools/blob/master/lv2/lv2_list_plugin_presets.py

**Comment by drobilla** [comment]
Confirmed fixed with latest master, if the explicit `Node` construction issue (which will now cause a hard error) is fixed.

Thanks.
