### ISSUE TITLE
Connect audio files and/or JACK ports to a plug-in using the Python binding

### ISSUE THREAD

**Issue by s-leroux** [drobilla/lilv#6]
Hi David,

I've built the latest `lilv` bindings for Python3 to experiment a little with it.
Things start to take place in my mind, but I'm stuck since I can't understand how to connect a plugin audio input/output  ports to the outside world.

In the example below, I would like to connect the ports 0 and 1 to the audio file `/tmp/test.wav` and the ports 2 and 3 to the system's `playback_1` and `playback_2` JACK ports. Is it possible? And if it is, how?

```
>>> import lilv
>>> [calfrev] = [p for p in world.get_all_plugins() if p.get_name() == 'Calf Reverb']
>>> for idx in range(0, 16): print(idx, calfrev.get_port(idx).get_name())
... 
0 In L
1 In R
2 Out L
3 Out R
4 0dB
5 Wet amount
6 Output
7 Decay time
8 High Frq Damp
9 Room size
10 Diffusion
11 Wet Amount
12 Dry Amount
13 Pre Delay
14 Bass Cut
15 Treble Cut
>>> instance = lilv.Instance(calfrev, 48000)
>>> instance.connect_port(0, ... <<- I'm stuck here
```

**Comment by s-leroux** [comment]
Ok, I found some elements of answer here:
https://github.com/drobilla/lilv/blob/master/bindings/python/lv2_apply.py

Still no idea about JACK port connection though.

**Comment by drobilla** [comment]
Yep. `lv2_apply.py` is the in-tree example of connecting ports to audio.  In general lilv doesn't do anything particularly clever here, it's up to you to get a float array somehow.

I don't know about any Python bindings for Jack, sorry.  Some might exist, but maybe not, since Python is not safe to use in realtime code so there's not much incentive to make any.

**Comment by s-leroux** [comment]
Thanks for the reply David.

> Yep. lv2_apply.py is the in-tree example of connecting ports to audio. In general, lilv doesn't do anything particularly clever here, it's up to you to get a float array somehow.

OK.

> I don't know about any Python bindings for Jack, sorry.

No problem, I was mainly concerned about using JACK to pass the output through some patch bay. But it was not a particularly clever solution since I'm mostly interested in batch processing.

> since Python is not safe to use in realtime code so there's not much incentive to make any.

Indeed. My goal was to find a simple way of restoring the state of a plug-in for applying the same treatment to a set of audio files. But if you follow the lv2plug.in devel list , you may have seen I switched my mind and considering now using the C API (probably by modifying the `lv2file` command line tool)

Speaking of the plug-in state, I also noticed in the Python binding docs, the `State` class was marked "TODO". Does that mean it is not documented, unstable or just not implemented?

**Comment by drobilla** [comment]
Just not implemented.  You could maybe make it work by using the raw bindings, but a nice class interface for this still needs doing.

**Comment by SpotlightKid** [comment]
@s-leroux Maybe a bit late, but to query and manipulate JACK ports, you could use the [JACK-Client](https://github.com/spatialaudio/jackclient-python) Python library.

**Comment by drobilla** [comment]
Closing this as out of scope for now, though I'd be happy to accept a Python example that uses JACK.

Please open a separate issue for the state issue if that's important.
