### ISSUE TITLE
No documentation.

### ISSUE THREAD

**Issue by reduz** [drobilla/lilv#7]
I would like to implement this in an old sequencer I wrote. 

However, there is zero documentation on lilv or ladspav2 as a host and my time to work on this is limited. A reference by itself is useless and the examples are incredibly complex. Implementing LV1 15 years ago was a tiny fraction of the code, and not even wrapper libs were needed.

A tutorial on setting up, using it, discovering, bringing up an UI, etc. or at least what each thing is supposed to be would be appreciated, otherwise I'm afraid even supporting Linux is just a bad idea.

I'm surprised you spent so much writing example code but not even dedicated to explain even an overview on how the library is supposed to work.

If you don't have time for this, I suggest you make Github the official development platform (it's 2018, hosting the project on hour own website is very 1999), put documentation in here in Markup and ask the community for contributions on this aspect.

Best

**Comment by giuliomoro** [comment]
I implemented a host in a few hours last night, using `utils/lv2apply.c` as a starting point and the reference to fill-in the gaps

**Comment by giuliomoro** [comment]
And, by the way, I am not sure why you come here with such an aggressive tone. David has put so much of his time into a number of open source projects, making it easier for other people to get started with `lv2`, and the least you could do is be grateful.

Hopefully you will find some more time to work on this project in the future and share your results with the online community, to make other people's life easier when getting started with `lilv`.
