### ISSUE TITLE
lv2apply: Default values are used only when they are nan

### ISSUE THREAD

**Issue by giuliomoro** [drobilla/lilv#8]
This line https://github.com/drobilla/lilv/blob/master/utils/lv2apply.c#L160
```
 port->value     = isnan(values[i]) ? values[i] : 0.0f;
```
`float* values` are the default value for the ports.
The line stores the port's default value in the `port` only if it is `nan`. I cannot see how this is the expected behaviour. I think it should be 
```
 port->value     = isnan(values[i]) ? 0.0f : values[i];
```
or am I missing something?

**Comment by drobilla** [comment]
Whoops!  Seems you're right, I have no idea how that happened...

Thanks
